### ISSUE TITLE
Add copyright information in About dialog

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/icsx5#148]
I came across this because HUAWEI complained for "missing" copyright information. Missing in the sense that no entity is responsible for the uploaded app (and visible inside the app) - which is not compliant with their app distribution policy (anymore?). I also had to add our business license for DAVx5 last year and did so for ICSx5 now.

Currently we only have the GPLV3 link in the About dialog (for all stores the same) without any legal entity or names. I think we need to add bitfire as copyright owner for this like we do it with DAVx5. But I also think that we can keep the GPLV3 link. So then it is clearly shown that bitfire licenses the software under GPL and we also don't have to make flavors in Android studio to deal with different information for certain stores.

![grafik](https://user-images.githubusercontent.com/3578887/232196354-4b592b48-a3be-4aa6-9638-46ffb0aaa72c.png)
↓
![grafik](https://user-images.githubusercontent.com/3578887/232196638-3ab053bd-c3f3-4af0-ae14-27e3ec80d130.png)

**Comment by ArnyminerZ** [comment]
I think the quickest workaround is to use the `withAboutSpecial2` of `LibsBuilder`. It looks like this:
![copy](https://user-images.githubusercontent.com/12086466/232321500-61fce402-b579-4dec-8464-30a59b236b03.png)

![copy_text](https://user-images.githubusercontent.com/12086466/232321502-37411a64-3d17-42b2-b060-60d5ee8c560a.png)

Otherwise we can simply update the "Subscribe to Webcal feeds" text with the copyright notice. However, we should remove the existing translations, or rename the string to Transifex takes care of the update.
