### ISSUE TITLE
Fix code scanning alert - `TrustManager` that accepts all certificates

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/icsx5#161]
Tracking issue for:
- [ ] https://github.com/bitfireAT/icsx5/security/code-scanning/2

**Comment by ArnyminerZ** [comment]
@rfc2822 @sunkup can you take a look at this? I think it's a false positive, we are filtering and throwing `CertificateException`

**Comment by rfc2822** [comment]
Yes, it's a false positive, probably caused because our CustomCertManager's `checkServerTrusted` doesn't throw `CertificateException` directly, but calls `checkCustomTrusted` which throws the exception.

However the design of `checkServerTrusted` and `checkCustomTrusted` should become improved by bitfireAT/cert4android#12 when we don't need those AIDL callbacks anymore.

**Comment by ArnyminerZ** [comment]
Then I think this can be closed 😉
