### ISSUE TITLE
Unable to dismiss info card after tapping notification

### ISSUE THREAD

**Issue by sunkup** [bitfireAT/icsx5#296]
Steps to reproduce:
1. Create a subscription
2. Turn off network access
3. Try to sync the subscription
4. Tap the notification that appears
5. You are presented with the info card which can't be dismissed
 

_Originally posted by @UserX404 in https://github.com/bitfireAT/icsx5/discussions/206#discussioncomment-9178953_

> I got notification from icsx5 about unable to resolve host blablabla. When i click on this notification a grayed out screen is shown with a info box in the top. Talking about unable to resolve host .... with "view details" on the botom left and "ok" on the bottom right.
It's not possible to click on OK or leave that screen. I need to swipe the screen from the recent apps or force-close be long click on back button.

**Comment by UserX404** [comment]
I want to add some further proposal to this.
Despite the OK-button was responsive before, meant bringing me to the screen with the red "could not resolve..." text, it was also not possible to trigger a refresh on that screen due to there is no refresh/retry button or swipe-down-to-refres gesture registered.
Then I need to close, find icsx5 within the app list, open it, swipe down to refresh.
It would be an welcome improvement if it's possible to re-trigger a retry on that screen.

I usuall turn off internet connection over-night and after enable it again in the morning there are these "could-not-resolve" notifications every now and then.

**Comment by ArnyminerZ** [comment]
> I want to add some further proposal to this.

I agree completely with this, there should be an easier way to refresh. However, right now when the notification is tapped, the screen that is launched is the edit one. I think this is not ideal, since usually you wouldn't want to edit the subscription, just to take a look, and refresh, so the subscriptions list screen should be launched instead.

For that reason, some modifications must be made, which I think are outside of the scope of this issue, so I'll create a new one with this feature request.
