### ISSUE TITLE
Provide backup over Backup API

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#4]
Subscriptions and settings could be saved using the [Android Backup API](https://developer.android.com/guide/topics/data/backup) (also as a "test" for DAVx⁵ backup).

Automatic file backup should handle everything except the actual subscriptions because they reside in the calendar provider.

Maybe this can be implemented this way:
1. Before the backup runs, ICSx⁵ saves the subscriptions to a private JSON file.
2. Normal file backup runs.
3. After a backup is restored, ICSx⁵ parses the JSON file and adds the subscriptions again.

Maybe credentials should only be saved when [clientSideEncryption is available](https://developer.android.com/guide/topics/data/autobackup#define-device-conditions).

Depends on #76

**Comment by ArnyminerZ** [comment]
Depends on #76

**Comment by rfc2822** [comment]
> Depends on #76

I think this must be in the first message of the issue (the scanner will only scan the first message)

**Comment by ArnyminerZ** [comment]
- [ ] `BackupAgent` for setting data to back up.
  - [ ] Fetching contents from database.
  - [ ] Parsing contents to JSON.
  - [ ] Storing data with agent.
- [ ] Manual backup creation.
- [ ] Manual backup recovery.

**Comment by ArnyminerZ** [comment]
#119 actually works. Backup method:
1. Launch the app, and create a subscription.
2. Run `adb shell bmgr enabled`. This should return `Backup Manager currently enabled`, otherwise backup must be enabled in system settings.
3. Run `adb shell bmgr backupnow at.bitfire.icsdroid`. This creates the backup. The response should be something like:
    ```
    Running incremental backup for 1 requested packages.
    Package @pm@ with result: Success
    Package at.bitfire.icsdroid with progress: 512/54784
    Package at.bitfire.icsdroid with progress: 56832/54784
    Package at.bitfire.icsdroid with result: Success
    Backup finished with result: Success
    ```
4. Run `adb shell dumpsys backup`, and search for the line `Current:`, followed by an hexadecimal string. Copy it, it's the backup token.
    _`adb shell dumpsys backup | grep Current:` can also be used, it will display the token directly_
5. Erase app data. _Now the app doesn't have any subscription._
6. Run `adb shell bmgr restore <token> at.bitfire.icsdroid`.
7. Launch the app, the old subscription should be ready. Also permissions have been reset.
