### ISSUE TITLE
(Dark mode?) after installing doesn't show calendar list

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#61]
1. (Switch device to dark mode)
2. Install latest ICSx5 from Google Play, launch it, allow calendar access
3. Add a subscription
4. The subscription is there, but not shown – only a black screen, see screenshot below.

When the theme is changed to light theme _or_ when ICSx⁵ is killed in the task manager and started again, everything works.

![Screenshot_1662483490](https://user-images.githubusercontent.com/156167/188696290-366ccf51-242a-4df9-8d08-88e0cefbd4a5.png)

**Comment by ArnyminerZ** [comment]
Turns out this isn't enough. Running `SyncWorker` doesn't update the UI properly, even though logs show that the new endpoints are being fetched. It just happens the first time you launch the app. When you add a calendar, it doesn't show up. If you remove the calendar, and try adding a new one, it shows up properly.
